name: OSDev CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test KenOS
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      GITHUB_DIR: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
        docker pull memegauste/kenos-build:alphadocker
        docker run -w $GITHUB_DIR -v $GITHUB_DIR:$GITHUB_DIR memegauste/kenos-build:alphadocker /bin/bash -c "make -j$(nproc) -k"

    - uses: actions/upload-artifact@v4
      name: Upload current KenOS build
      with:
        name: kenos.iso
        path: ./kenos.iso
